import Head from 'next/head';
import { useState } from 'react';


export default function Home() {

  //declarar uma nova variavel dados com state e atribuir o objeto
  const [data, setData] = useState({
    name: '',
    email: ''
  });

  // receber os dados dos campos do formulario
  const valueInput = (e) => setData({ ...data, [e.target.name]: e.target.value});

  // Execultar a função quando o usuario clicar no botão do fomrulario
  const addUser = (e) =>{
    
    //Bloquear o recarregamento da pagina
    e.preventDefault();

    console.log("Enviar para a API");
  }

  return (
    <>
      <Head>
        <title>CRUD</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <h2>Cadastrar Usuário</h2>

        <form onSubmit={addUser}>

          <label> Nome: </label>
          <input type ='text' name='name' placeholder='Digite o Nome' onChange={valueInput} value={data.name}/><br /><br />
          <label> Email: </label>
          <input type ='text' name='name' placeholder='Digite o Email' /><br /><br />
          <button>Enviar</button><br /><br />

        </form>

      </main>
    </>
  )
}
